BachatGat360/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Dashboard.urls'))
]

Dashboard/urls.py
from django.urls import path

from Dashboard.views import *

app_name = 'Dashboard'  # APP_NAME

urlpatterns = [
    path('', dashboard, name='home'),

]

Home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^text/$', views.text, name='text'),
    url(r'^json/$', views.json, name='json'),
]

Dashboard/models.py
from django.contrib.auth.models import User
from django.db import models


class Trans(models.Model):
    pass

Dashboard/views.py
from django.shortcuts import render


# Create your views here.
def dashboard(request):
    return render(request, 'Dashboard/main.html')

Home/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, 'Home/index.html')


def text(request):
    return render(request, 'Home/demo.txt')


def json(request):
    return render(request, 'Home/demo.json')

Dashboard/templates/Dashboard/main.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
</head>
<body>
<h1>Hello</h1>
<a href="{% url 'Dashboard:home' %}">a</a>
</body>
</html>

Home/templates/Home/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<h1>Hello</h1>

<main>
    <div id='main_table'>
        <label for="tb_1_1">Sum 1 </label><input type="number" class="pad" id="tb_1_1" value="0"><br>
        <label for="tb_1_2">Sum 2 </label><input type="number" class="pad" id="tb_1_2" value="0"><br>
        <label for="tb_1_3">Sum 3 </label><input type="number" class="pad" id="tb_1_3" value="0"><br>
        <label for="tb_1_4">Total </label><input type="number" class="pad" id="tb_1_4" value="" disabled><br>
    </div>
    <br>
    <div id="content">
        <div id="text-replace"></div>
        <button id="button">Get Text File</button>
    </div>
</main>
<script src="{% static 'vendor/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script type="text/javascript">
    document.getElementById('button').addEventListener('click', loadText);

    function loadText() {
        // Create XHR
        let xhr = new XMLHttpRequest();


        //Open
        xhr.open('GET', '{% url 'home:json' %}', true);

        //Error
        xhr.onerror = function () {
            console.log('Request Error');
        };
        //Progress
        xhr.onprogress = function () {
            //pass
        };
        let user = JSON.constructor(test
        );
        xhr.onload = function () {
            if (this.status === 200) {
                let user = JSON.parse(this.responseText);
                $('#text-replace').append(user.first_name + user.contact);
            }
        };
        xhr.send();
    }
</script>
</body>
</html>